version: '3'
services:
  db:
    image: postgres:14.4-alpine
    container_name: honey-ryder-task-db
    ports:
      - 15432:5432
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
