// <auto-generated />
using System;
using HoneyRyderTask.Infrastructure.PostgreSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HoneyRyderTask.Infrastructure.Migrations
{
    [DbContext(typeof(HoneyRyderTaskDbContext))]
    partial class HoneyRyderTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HoneyRyderTask.Infrastructure.PostgreSQL.DataModels.Tasks.TaskDataModel", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("task_id");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("Date")
                        .HasColumnName("completion_date");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("Date")
                        .HasColumnName("creation_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("Date")
                        .HasColumnName("due_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("title");

                    b.HasKey("TaskId");

                    b.ToTable("tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
